### PR TITLE
Fix paths to quoted, so iso can be compiled in any path [part 1]

### PR DESCRIPTION
**Pull request by keybreak**
@killajoe @manuel-192 
Well, you know the drill, i won't repeat whole text again :upside_down_face: 

This part contains all files that miss those quotes currently, except `run_before_squashfs.sh`, so at least these part can be easily accepted, it clearly won't affect build in any way, see the diff it's not much...

`run_before_squashfs.sh` up to speed with current changes will come later :partying_face:

### CODE REVIEW

**Comment by killajoe** [comment]
hmm this guy again ;) now without changing all the run_before_squashfs script.. looks more lean

**Comment by killajoe** [comment]
i will try that .. but before merging i nee dto test ;)

**Comment by keybreak** [comment]
Of course :wink: 
I always test before as well... :upside_down_face:

**Comment by killajoe** [comment]
tested and merged..

**Comment by keybreak** [comment]
That's one small step for a man, a giant leap for mankind :rocket:

**Pull request merged**
