### PR TITLE
add packages needed for hardware video decoding

### PR DESCRIPTION
**Pull request by nachoslover813260**

### CODE REVIEW

**Comment by killajoe** [comment]
is there a need for this on the ISO itself?  and all possible GPU/drivers need this?

**Comment by nachoslover813260** [comment]
In my opinion yes, manjaro and archinstall also included this it would be unnecessary for the end user having to install this package manually, and it would be handy for using the live environment
This is for both amd and intel gpu

**Comment by killajoe** [comment]
We try to have the bare minimum of packages preinstalled.
So if there is no default usecase we will not go to add any package. 
In addition, this will need hardware detection to have only the one installed that is needed for the specific hardware. 
And to implement these beeing installed it is not the place to add them for installed system this packages here will only be for offline install and the ISO itself to install these on all install methods they need to go here in addition:

- https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/netinstall.yaml
- https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/netinstall-ce-base.yaml

**Comment by killajoe** [comment]
The right place to commit a PR on the installer would be this:
https://github.com/endeavouros-team/calamares

**Pull request closed without merging**
