### PR TITLE
Remove useless --ignore argument

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
-a = all
-A = almost all (no ./..)

### CODE REVIEW

**Comment by killajoe** [comment]
@manuel-192 ?
bash Meister ;)

**Comment by TruncatedDinosour** [comment]
Also, this if what I use for my ls shorthands
so if y'all want it:


```bash
alias ls='lsd --group-dirs --color=auto -Fh'
alias ll='ls -lF'
alias la='ls -lFA'
alias l='ll'
alias lf='ls -FA'
```

Lsd is just better ls: https://github.com/Peltoche/lsd

**Comment by TruncatedDinosour** [comment]
It also works with ls, though you will have to replace the `--group-dirs` argument with `-v` argument

**Comment by keybreak** [comment]
I believe such kinda of aliases should be left for user decision, as this is very personalized stuff anyway :upside_down_face:

**Comment by killajoe** [comment]
indeed but  .. the bash configuration is completely unsolved on the side of code.. it is working as it should for the user.. but totally mess how it is handled..

**Comment by TruncatedDinosour** [comment]
Okay, will close then

**Comment by killajoe** [comment]
okay .. i was not closing it to have a reminder on the bash thing ;)  but now .. i simply need to solve it i think?

**Pull request closed without merging**
